### ISSUE TITLE
QR code for URL

### ISSUE THREAD

**Issue by Yang-Tang** [aoles/shinyURL#3]
Thank you for this nice shiny package. It would be more insteresting to add an option to generate a URL QR code of current status of shiny app.

**Comment by aoles** [comment]
Hi @Yang-Tang,
thank you for your feedback!

I've just updated shinyURL to provide an easy way of capturing the URL inside the app's script. Starting from version 0.0.30, the function `shinyURL.server` returns a reactive expression evaluating to the app's URL. This gives direct access to the string containing the URL, making it easy to customize how it is displayed to the user.

A possible use case is to take the URL and use it to generate a QR code which will be displayed to the user instead of the default `shinyURL.ui` widget. The QR code itself can be created, for example, with the help of the R package [qrcode](https://cran.r-project.org/web/packages/qrcode/index.html), as illustrated in the following example. The size of the code can be controlled by setting `scale`.

``` r
library("shiny")
library("shinyURL")
library("qrcode")

shinyApp(
  ui = fluidPage(
    titlePanel("Old Faithful Geyser Data"),
    sidebarLayout(
      sidebarPanel(
        sliderInput("bins", "Number of bins:", min = 1, max = 50, value = 30),
        plotOutput("qrcode")
      ),
      mainPanel(
        plotOutput("plot")
      )
    )
  ),
  server = function(input, output) {
    url = shinyURL.server()

    output$plot <- renderPlot({
      x <- faithful[, 2]
      bins <- seq(min(x), max(x), length.out = input$bins + 1)
      hist(x, breaks = bins, col = 'darkgray', border = 'white')
    })

    qrcode = reactive( t(qrcode_gen(url(), plotQRcode = FALSE, dataOutput = TRUE)) )
    nc = reactive( ncol(qrcode()) )
    nr = reactive( nrow(qrcode()) )
    scale = 4

    output$qrcode <- renderPlot({
      par(mar=c(0,0,0,0))
      image(1L:nc(), 1L:nr(), qrcode(), xlim = 0.5 + c(0, nc()),
            ylim = 0.5 + c(nr(), 0), axes = FALSE, xlab = "", ylab = "",
            col = c("white", "black"), asp = 1)
    }, width = function() scale*nc(), height = function() scale*nr())
  }
)  
```

For an application in an interactive R markdown document, see the [example distributed with the package](https://github.com/aoles/shinyURL/tree/master/inst/examples/qrcode).

**Comment by Yang-Tang** [comment]
Thank you @aoles ! The code and documents are very useful.
